# pubse c.yaml for culture_lessons package

name: culture_lessons
description: A reusable package for culture and etiquette lessons data models.
version: 0.0.1
environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter